### ISSUE TITLE
University of Bath Quantum Hackathon

### ISSUE THREAD

**Issue by rryoung98** [qBraid/community#20]
From the organizers: **The goal of the event is to introduce University of Bath students to quantum technologies and quantum software.** 

It is currently being organized as a student collaboration between the Physics and Computer Science departments, but all students with previous coding experience are welcome. 

We are expecting around **100 participants**, thus making it a relatively small and local event. Ideally we would like to have 2 to 3 challenges, proposed by sponsors. The ideal scenario is for the sponsors to give an initial workshop introducing their work as an institution and their proposed challenge. This is the first time we run an event of such sort, and especially within the physics department there might be students who are unfamiliar with a hackathon format, therefore we have been asked by the relevant departments to make the challenges relatively short. 

Ideally the challenge or challenges will be completed by participants within 8 to 12 hours. All participants will come with different levels of coding experience and a big majority will have quantum physics notions, although those will be revised in some of the workshops we will organize alongside the industrial sponsor workshops.

**Comment by rryoung98** [comment]
# Event details
We approximate around 100 participants, and would like to offer 2-3 challenges with 3 possible
challenge categories:

## Challenges:

1) A challenge that focuses on a challenging software problem to solve, curated for students
with a lower understanding of Quantum physics and Quantum information, who have a
strong background in programming but need an introduction to the field.
2) A challenge that focuses on resolving a deeply physics oriented problem with existing
quantum software. This challenge should be curated towards physics students who have
lesser expertise in the coding field, but who have a strong understanding of quantum theory
(at an undergraduate level).
3) A challenge that is designed for undergraduate students with little experience in
programming and Quantum physics, but who still have an understanding an level of
expertise in these areas.

## Dates
We would like to organize this event during the 2nd weekend of February. Saturday would be
reserved for workshops, talks, and introductions, and Sunday would have a 12h coding challenge
period (from 8am to 8pm UK time) followed by a closing ceremony the following week.

**Comment by rryoung98** [comment]
@PrachiWomanium  Womanism Tasks:

Monitoring Discord
Answering any basic quantum computing questions.

**Comment by PrachiWomanium** [comment]
Avg Response Time: <2 hrs
Best time zone: CET
Assignee: TBD (Alex, Shaurya, Vardaan); Quals: QSilver experience; QBraid experience not necessary
**Task: Respond to all questions on Channel - (RIcky will add)**
Ricky to add PV to Discord. PV will add team. --> to do by Feb 6th.

**Comment by rryoung98** [comment]
Finished!
