### ISSUE TITLE
Adam (Haq) <> Alberto (QOSF,QUE,qBraid) <> Ricky (qBraid)

### ISSUE THREAD

**Issue by rryoung98** [qBraid/community#26]
qBraid, Adam Fattal, and @MaldoAlberto Alberto are leading a project to build a revamped [qbook.qbraid.com ](qbook.qbraid.com)

## Goal:
We want to submit a tutorial notebooks which are hosted on qbraid and incorporates some of the technological features in haq.ai such as the code judging with judge0.
![image](https://user-images.githubusercontent.com/32727721/218577477-c3800bef-531a-4723-ad18-9b3d0dfef6d3.png)

![image](https://user-images.githubusercontent.com/32727721/218578155-c4f254e7-901e-4505-8b49-204c0d834d51.png)

### @rryoung98  
- Building the integration of haq.ai
- Revamping qbook

### Adam
- Provide guidance on importing questions and the haq.ai code.

### @MaldoAlberto 
- Rally the community.
- Get people to submit tutorial notebooks that can be added to the platform which Ricky and Adam will build.

https://qce.quantum.ieee.org/2023/call-for-tutorials/

**Comment by kanavsetia** [comment]
stale issue, so, closing it!
