### ISSUE TITLE
[BUG] right-click menu for files behavior

### ISSUE THREAD

**Issue by TariniHardikar** [qBraid/community#31]
### Bug Title

if multiple files are selected, menu items aren't working consistently

### Category

Other

### Bug Description

If multiple files are selected, right-click menu tasks aren't consistently working. Duplicate and delete seems to work, but download and copy only works on one of the selected files.

![Screenshot 2024-10-04 at 10 52 04 AM](https://github.com/user-attachments/assets/1f2b2b9d-d8cf-41f5-94a1-578ed9088ef9)

On Safari.

**Comment by ryanhill1** [comment]
Closing as we've now reverted back to the legacy file-browser, so this should no longer be an issue.
