### ISSUE TITLE
Journal Club with QUE and qBraid

### ISSUE THREAD

**Issue by rryoung98** [qBraid/community#4]
We will do an event on December 12th.

We can invite Womanium, QOSF, QUE, and Unitary Fund.  CQTech

Junyu Liu

**Comment by rryoung98** [comment]
Let's meet every Wednesday 6pm and discuss how to organize the event.

**Comment by MaldoAlberto** [comment]
Yesterday we don'0t so the meeting :(  and I talk with PIQUE and they say 

That would be great! Maybe we could have one journal presentation from each of the organizers on different weeks or different months too
