### ISSUE TITLE
ask questions on discord

### ISSUE THREAD

**Issue by rryoung98** [qBraid/community#8]
what is your favorite framework using Qbraid?

How do you know about Qbraid ?

What was your first project using Qbraid?

if you have infinite credits in Qbraid what backend you would to use?

**Comment by MaldoAlberto** [comment]
add porposal for each day of the next week November 21 do question on discord server and add memes
 https://docs.google.com/document/d/1PfSUPF5qXGuvEarwpUuV7BqphJBRfIiz6E25Z0DPTMY/edit?usp=sharing
